services:
  upload:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./:/articles
      - venv:/articles/.venv
    working_dir: /articles/python
    command: poetry run python main.py

volumes:
  venv:
